name: TNTRun
main: tntrun.TNTRun
softdepend: [Multiverse-Core, MultiWorld, WorldEdit]
version: 1.1.devel
author: _Shevchik_
commands:
  trsetup:
    description: TNTRun arena setup commands
  tr:
    description: TNTRun game commands
    usage: Use /tr help to show all commands available in plugin.