name: TNTRun
main: tntrun.TNTRun
softdepend: [Multiverse-Core, MultiWorld, WorldEdit, Vault]
version: 1.1
author: _Shevchik_
commands:
  tntrunsetup:
    description: TNTRun arena setup commands
    aliases: trsetup
    usage: Command is invalid.
  tntrun:
    description: TNTRun game commands
    aliases: tr
    usage: Use /tr help to show all commands available in plugin.